### ISSUE TITLE
Build fails Ubuntu 20.04.1 R 4.0.2

### ISSUE THREAD

**Issue by jimr1603** [coolbutuseless/chipmunkcore#2]
I'm not sure if I've messed up the library install or if it's a package issue. I followed the Ubuntu instructions, and `devtools::install_github` failed. To get a better error message I cloned the repo and ran`devtools::build`. Error below:

```
Error in (function (command = NULL, args = character(), error_on_status = TRUE,  : 
  System command 'R' failed, exit status: 1, stdout + stderr (last 10 lines):
E> ** testing if installed package can be loaded from temporary location
E> Error: package or namespace load failed for ‘chipmunkcore’ in dyn.load(file, DLLpath = DLLpath, ...):
E>  unable to load shared object '/tmp/RtmpiHrUqO/Rinst2c5d119a89edc/00LOCK-chipmunkcore/00new/chipmunkcore/libs/chipmunkcore.so':
E>   /tmp/RtmpiHrUqO/Rinst2c5d119a89edc/00LOCK-chipmunkcore/00new/chipmunkcore/libs/chipmunkcore.so: undefined symbol: cpBodyGetTorque
E> Error: loading failed
E> Execution halted
E> ERROR: loading failed
E> * removing ‘/tmp/RtmpiHrUqO/Rinst2c5d119a89edc/chipmunkcore’
E>       -----------------------------------
E> ERROR: package installation failed
```

I can see cpBody*Set*Torque in `cpBody.c`, but not *Get*Torque.

**Comment by coolbutuseless** [comment]
Hi @jimr1603 - i've just pushed a change that I think fixes this issue: https://github.com/coolbutuseless/chipmunkcore/commit/97cc78ad3a68192f9c99cee93203510e20151dde

Any feedback would be appreciated.

**Comment by jimr1603** [comment]
Morning,

I get the same error. I'm going to spin up an AWS or something after work
to check it on a fresh machine

**Comment by jimr1603** [comment]
I poked it at lunch and got it working, following linux 1 not linux 2. I think I'll poke the linux 2 instructions on my other box and possibly submit a PR on those instructions.
